### PR TITLE
No ambermini

### PR DESCRIPTION
**Pull request by jaimergp**
Checklist
* [X] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

`ambermini` used to be a minified distribution of `ambertools` used in some packages (specially in the `omnia` channel). This is incompatible with the full `ambertools` distribution so we are using the `run_constrained` trick to explicitly declare it as such instead of crossing our fingers :D

### CODE REVIEW

**Comment by jaimergp** [comment]
@conda-forge-admin, please rerender

**Comment by simonbray** [comment]
If you wanted to condense the test a bit, I think `! conda install -c omnia ambermini` would work too. Though the current test is absolutely fine. Actually, I'm a bit surprised conda doesn't have something like `expect_failure` for tests.

**Comment by jaimergp** [comment]
> If you wanted to condense the test a bit, I think `! conda install -c omnia ambermini` would work too. Though the current test is absolutely fine. Actually, I'm a bit surprised conda doesn't have something like `expect_failure` for tests.

Oh, silly me, I didn't think of that and ended up overengineering it. I'll make that change before the merge. Thanks!

**Comment by simonbray** [comment]
Now I think of it, `conda install -c omnia ambermini 2>&1 | grep -q "PackagesNotFoundError"` would be better.

**Comment by jaimergp** [comment]
Well, the `conda install` solver will do whatever needed to be able to install ambermini next to ambertools which means it will downgrade to the non-`run_constrained` version if needed.

I have tested locally and you have to really specific about what you want:

This should fail as expected:

```
conda install omnia::ambermini 'conda-forge::ambertools>=19.11_*5'
```

I doubt this will help much, but I'll merge anyway. AT20 is being released soon and it will be marked as incompatible with ambermini too, but in that case it will be easier to pin because of the major version change (instead of the unnoticeable build number).

**Pull request merged**
