### PR TITLE
Use MINOR version number to automatically update source to corresponding patch release version

### PR DESCRIPTION
**Pull request by jchodera**
@simonbray: Here's a concrete implementation of what I suggested in https://github.com/conda-forge/ambertools-feedstock/issues/10

This PR adds logic to the build script to automatically update the source to the patch release corresponding to the MINOR version numbers, so that 19.0 will be the unpatched release, 19.1 will include the first patch, and 19.9 will reproducibly include the first nine patches (currently the latest version).

This should allow us to easily build any needed patch releases and keep the versioning consistent and reproducible.

### CODE REVIEW

**Comment by simonbray** [comment]
Looks good to me. The python3.6 build is failing but this seems to just be because the process of downloading the patch is timing out.

**Comment by simonbray** [comment]
@conda-forge-admin, please rerender

**Comment by jchodera** [comment]
One question is whether we want to build versions for all patch releases (19.0 - 19.9) to make it easier to reproduce, or if we should just build 19.0 and 19.9 (latest) for now, and then build intermediate versions if requested.

We might also ask @dacase if there's an easy way for us to be automatically notified when new patches become available.

**Comment by jchodera** [comment]
> Looks good to me. The python3.6 build is failing but this seems to just be because the process of downloading the patch is timing out.

I wonder if we could add some logic to simply retry the patch application if it fails once or twice.

**Comment by dacase** [comment]
@jchodera asked "One question is whether we want to build versions for all patch releases (19.0 - 19.9) "

I'd vote to just have the latest version.  While I appreciate that having earlier versions might make it easier to reproduce errors, if there is any question about that, we have always asked users to upgrade to the most current (minor) version.  To put that in another way, I can't remember (offhand) any case where being able to go back to an earlier release point really helped in debugging.  But I'm open to counterarguments.  To me, though, keeping old versions around is something that sounds good, but adds to the build burden and doesn't really help that much.

**Comment by dacase** [comment]
@jchodera  wrote: "if there's an easy way for us to be automatically notified when new patches become available?"  We could certainly figure this out; right now, I'd be happy to send an email to some address with such notifications (admittedly an error-prone solution).  Or, some script could do  "update--amber --show-unapplied-patches" in a cron job, and trigger a new build when new patches show up.

[FWIW: I'm pushing to put the released version of AmberTools onto github.  Then the workflow would just be to 'git pull' and check to see if changes are made.  Plus, it's easy to just place a "watch" on a repo to be informed when changes are made.  But I still have to convince Jason....]

**Comment by dacase** [comment]
Finally: do you know when the patch requests timed out?  If it was a couple of days ago, that was likely the result of a web configuration glitch, which has now been fixed.  If it is happening now (e.g.10/21/2019) then it's something else.  Any details on the error (python traceback, etc.) might be helpful.

**Comment by simonbray** [comment]
It would be great to see the AmberTools code on GitHub.

The time-outs were occurring today with this error (copied from the Azure logs):
```
Applying AmberTools 19/update.4
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/ambertools_1571672803835/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/home/conda/feedstock_root/build_artifacts/ambertools_1571672803835/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/conda/feedstock_root/build_artifacts/ambertools_1571672803835/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/conda/feedstock_root/build_artifacts/ambertools_1571672803835/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/conda/feedstock_root/build_artifacts/ambertools_1571672803835/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/home/conda/feedstock_root/build_artifacts/ambertools_1571672803835/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/conda/feedstock_root/build_artifacts/ambertools_1571672803835/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/home/conda/feedstock_root/build_artifacts/ambertools_1571672803835/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/home/conda/feedstock_root/build_artifacts/ambertools_1571672803835/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./update_amber", line 26, in <module>
    app.mainloop()
  File "/home/conda/feedstock_root/build_artifacts/ambertools_1571672803835/work/updateutils/main.py", line 528, in mainloop
    self.update_to(opt.update_to)
  File "/home/conda/feedstock_root/build_artifacts/ambertools_1571672803835/work/updateutils/main.py", line 49, in newfcn
    fcn(self, *args, **kwargs)
  File "/home/conda/feedstock_root/build_artifacts/ambertools_1571672803835/work/updateutils/main.py", line 361, in update_to
    self._update_ambertools(int(updateto[0]))
  File "/home/conda/feedstock_root/build_artifacts/ambertools_1571672803835/work/updateutils/main.py", line 49, in newfcn
    fcn(self, *args, **kwargs)
  File "/home/conda/feedstock_root/build_artifacts/ambertools_1571672803835/work/updateutils/main.py", line 234, in _update_ambertools
    last)
  File "/home/conda/feedstock_root/build_artifacts/ambertools_1571672803835/work/updateutils/main.py", line 49, in newfcn
    fcn(self, *args, **kwargs)
  File "/home/conda/feedstock_root/build_artifacts/ambertools_1571672803835/work/updateutils/main.py", line 228, in _update_tree
    first=localap.last() + 1, last=last, apply_=True)
  File "/home/conda/feedstock_root/build_artifacts/ambertools_1571672803835/work/updateutils/downloader.py", line 108, in new_fcn
    return fcn(*args, **kwargs)
  File "/home/conda/feedstock_root/build_artifacts/ambertools_1571672803835/work/updateutils/repos.py", line 285, in download_patches
    (self.reponame, self.prefix, num))
  File "/home/conda/feedstock_root/build_artifacts/ambertools_1571672803835/work/updateutils/downloader.py", line 129, in __init__
    self.url = urlopen(url)
  File "/home/conda/feedstock_root/build_artifacts/ambertools_1571672803835/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/home/conda/feedstock_root/build_artifacts/ambertools_1571672803835/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/home/conda/feedstock_root/build_artifacts/ambertools_1571672803835/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/home/conda/feedstock_root/build_artifacts/ambertools_1571672803835/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/home/conda/feedstock_root/build_artifacts/ambertools_1571672803835/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/home/conda/feedstock_root/build_artifacts/ambertools_1571672803835/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error timed out>
Traceback (most recent call last):
  File "/opt/conda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 449, in main
    execute(sys.argv[1:])
  File "/opt/conda/lib/python3.7/site-packages/conda_build/cli/main_build.py", line 440, in execute
    verify=args.verify, variants=args.variants)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/api.py", line 209, in build
    notest=notest, need_source_download=need_source_download, variants=variants)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 2339, in build_tree
    notest=notest,
  File "/opt/conda/lib/python3.7/site-packages/conda_build/build.py", line 1487, in build
    cwd=src_dir, stats=build_stats)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/utils.py", line 399, in check_call_env
    return _func_defaulting_env_to_os_environ('call', *popenargs, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/conda_build/utils.py", line 379, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
```

**Comment by simonbray** [comment]
Great, tests are passing! Do you want to merge this already or wait for the OSX builds? Either is fine with me.

**Comment by dacase** [comment]
Let me know which repo I should be using for OSX tests: one under github.com/simonbray(?)

I'm a little mystified why patches are timing out: we haven't had any complaints from our users about this, so this is either something new, or something in your build environment....or ???

**Comment by simonbray** [comment]
You could start from the pull request I made here: https://github.com/conda-forge/ambertools-feedstock/pull/11, on the `fix-1` branch.

Not sure about the time-outs. On the conda-forge gitter channel it was mentioned that Azure has had some issues recently (build times have also been extremely long) so it could be linked to that rather than a problem on your side.

**Comment by jchodera** [comment]
> Great, tests are passing! Do you want to merge this already or wait for the OSX builds? Either is fine with me.

How about we merge this in now and then bring the changes into the `osx` PR? That way, we'll consistently build the same major.minor versions.

**Comment by simonbray** [comment]
Sounds good, thanks @jchodera!

**Comment by jchodera** [comment]
Thanks! Looks like this successfully deployed:
https://anaconda.org/conda-forge/ambertools/files

**Pull request merged**
