### PR TITLE
Testing builds for AT20

### PR DESCRIPTION
**Pull request by jaimergp**
Checklist
* [X] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jaimergp** [comment]
Looks like the Docker image is not able to allocate that many files, and it runs out of space. It does run on MacOS, and with no failures.

I have run the Linux-64 builds (py37) locally and didn't find any errors either.

**Comment by jaimergp** [comment]
Full log for the test suite in AT20RC2 (`cpinutil.py` patch is disabled) uploaded here for reference purposes:

[2020-04-24_06-49-17.zip](https://github.com/conda-forge/ambertools-feedstock/files/4529016/2020-04-24_06-49-17.zip)


Trying now with the RC3.

**Comment by jaimergp** [comment]
Aiming to merge later today unless there's anybody against it, @conda-forge/ambertools !

**Comment by simonbray** [comment]
> Aiming to merge later today unless there's anybody against it, @conda-forge/ambertools !

Looks good to me, glad to see you got all those patches pushed upstream.

**Pull request merged**
