### PR TITLE
Fix/relax parmed pins

### PR DESCRIPTION
**Pull request by mikemhenry**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by mikemhenry** [comment]
```
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/ambertools_1680042506198/test_tmp/run_test.py", line 14, in <module>
    import sander
  File "/home/conda/feedstock_root/build_artifacts/ambertools_1680042506198/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_place/lib/python3.10/site-packages/sander/__init__.py", line 5, in <module>
    from parmed.utils.six import string_types
ModuleNotFoundError: No module named 'parmed.utils.six'
```
Going to see if I can patch this or fix upstream

**Comment by mattwthompson** [comment]
Commenting because I'm curious how this works.

I thought the vendored version wasn't built? https://github.com/conda-forge/ambertools-feedstock/blob/ed56ef1fd7158c287d6374342dde9ff09e89032f/recipe/patches/do_not_install_vendored_parmed.patch

**Comment by ijpulidos** [comment]
@mattwthompson You are right, the issue here is that you can get conflicting environments if you try to install parmed 4 in them. An old version of  `ambertools` with the vendored `parmed` will get pull (such as 20.9 in our case in https://github.com/choderalab/perses/actions/runs/4550979162/jobs/8024534545#step:7:51

**Comment by jaimergp** [comment]
Is AT 22 known to be compatible with `parmed` 4? Otherwise this cannot be accepted.

**Comment by jaimergp** [comment]
I updated the parmed pins on #102, thanks @swails

**Comment by mikemhenry** [comment]
Closing in favor of https://github.com/conda-forge/ambertools-feedstock/pull/108

**Pull request closed without merging**
