### PR TITLE
Update 23 final

### LINKED ISSUE #97: A release candidate for AmberTools23 is now available
### Comment:

@jaimergp The first release candidate for AmberTools23 is now available:

wget https://ambermd.org/downloads/AmberTools23_rc1.tar.bz2

Are you (or someone else connected to this github page) still able and willing to work on this?
You could skip this RC if you wish...a second one should be ready in a week or so.  Let me know what I can do to help out.

One change from AmberTools22 is that the NAB compiler is no longer a part of the package.  This should be a simplification, and means that users no longer need to the compilers as well as the ambertools package itself.

### PR DESCRIPTION
**Pull request by jaimergp**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

Closes #97

### CODE REVIEW

**Comment by jaimergp** [comment]
Large diff due to bringing changes from `rc` here. The real diff is 5c6a7d7.

**Comment by jaimergp** [comment]
See this commit message:https://github.com/conda-forge/ambertools-feedstock/commit/2e3abe6863c387c92f126a99eb73472a2bbcde87#comments

**Comment by mattwthompson** [comment]
Did CI run? I don't see any status checks on commit 2e3abe6 or the feedstock https://dev.azure.com/conda-forge/feedstock-builds/_build?definitionId=6854


Oh, wait, I see now you kicked it yourself

**Comment by jaimergp** [comment]
Yea, had to retrigger manually; sometimes the CI events are dropped but an empty commit fixes it.

**Comment by mattwthompson** [comment]
I'm confused as well. In my experience it takes less than 2-3 hours, and never this long (if that is the reason, I'm skeptical)

The re-run of CI that Jaime did appears to have worked: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=700855&view=results

But the files are not there: https://anaconda.org/conda-forge/ambertools/files

I haven't seen this before - I've seen the builds fail and not appear, but not pass and fail to appear. Okay, now that I'm typing this, I realize that GitHub had an outage earlier today around this time. I wouldn't think that's the cause since I thought the tarball just needs to move from Azure to Anaconda Cloud, but maybe that's all done by a bot on GitHub, I don't know. My next recourse is checking the gitter channel (at [this](https://app.gitter.im/#/room/#conda-forge:matrix.org) link) where, if there is a widespread problem, somebody else will have shouted it out.

So you're not alone - I've been working on conda packaging for several years and I'm stumped. Sorry I couldn't be more helpful, but Jaime probably knows what's going on here.

**Comment by jaimergp** [comment]
Nah, nothing weird due to outages, just a mistake I made. I had enabled a setting to prevent accidental uploads when I created the `rc` branch, and then forgot to revert once I merged that to `main`. Added one more commit with the fix. Things should be there in ~1h. Sorry!

**Comment by mattwthompson** [comment]
I see everything online now!

**Pull request merged**
