### PR TITLE
Build 21.0

### PR DESCRIPTION
**Pull request by jaimergp**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jaimergp** [comment]
@conda-forge-admin, please rerender

**Review by simonbray — APPROVED** [review]

**Comment by jaimergp** [comment]
We will need a new `parmed` release before this is merged, since there are some changes that need to be upstreamed.

**Comment by jaimergp** [comment]
@swails is [3.4.1](https://github.com/ParmEd/ParmEd/releases/tag/3.4.1) the release we needed for this?

**Comment by swails** [comment]
> @swails is [3.4.1](https://github.com/ParmEd/ParmEd/releases/tag/3.4.1) the release we needed for this?

Yes.  AmberTools 21 will contain (exactly) ParmEd 3.4.1

**Comment by jaimergp** [comment]
Seems to work! I'll merge on Monday!

**Pull request merged**
