### PR TITLE
Attempt osx build and other changes

### PR DESCRIPTION
**Pull request by simonbray**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Build for OSX and make other changes (version number, license, maintainers).

### CODE REVIEW

**Comment by simonbray** [comment]
@conda-forge-admin, please rerender

**Comment by simonbray** [comment]
ping @dacase @jchodera @slochower. I also posted in the conda-forge gitter channel to request some assistance.

**Comment by beckermr** [comment]
It looks like the compiler is not setting the rpath here. You need something like `-Wl,-rpath,${PREFIX}/lib` in the compiler flags. The compiler packages inject this into the env in `LDFLAGS` etc already. So usually this means that the internal build system (i.e., ambertools in this case), needs to be told to use those flags.

Does this make sense?

**Comment by simonbray** [comment]
Yes, it does make sense, thanks. I'll have a go and might get back to you later.

**Comment by dacase** [comment]
Here's what I get on OSX 10.15 using the simonbray/fix-1 branch:
`Testing mixed C/Fortran compilation:
     x86_64-apple-darwin13.4.0-clang -fPIC -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE  -c -o testp.c.o testp.c
     $BUILD_PREFIX/bin/x86_64-apple-darwin13.4.0-gfortran -fPIC -O0 -c -o testp.f.o testp.f
     x86_64-apple-darwin13.4.0-clang -fPIC -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -o testp testp.c.o testp.f.o -L$BUILD_PREFIX/lib/gcc/x86_64-apple-darwin13.4.0/7.3.0/../../../ -lgfortran -w
dyld: Library not loaded: @rpath/libgfortran.4.dylib
  Referenced from: /Users/case/miniconda/conda-bld/ambertools_1571749601831/work/amber18/AmberTools/src/./testp
  Reason: image not found
Error: Unable to compile mixed C/Fortran code.`

So, the `@rpath` stuff is not getting added to the compiler flags correctly.  I think this is an error in the "configure2" script in AmberTools.   I'll try to create an upated "configure.patch" script to see if I can make any progress here.  But I'm really treading on unknown ground with `@rapth` stuff, and with using conda compilers rather than ones I am familiar with, so no promises.

**Comment by jchodera** [comment]
Any other ideas for how to move forward here?

@jaimergp: Any insight?

**Comment by dacase** [comment]
I'm stumped here--note that the error has nothing to do with Amber at all: the configure script is just trying to use the conda-supplied fortran compiler to compile a 3-line "hello world" test program.  The error message is given two comments above.

So, any experience I have as an Amber developer is not going to be of any help: we need someone who understands conda builds.  If I use my local gfortran compiler, everything is fine; it's when
I try to list the gfortran compiler as a prerequisite in meta.yaml, *and* try to build a system that has a C main program that accesses a Fortran subroutine, that the problem is triggered.

To try to make things easier to reproduce, here are the `testp.c` and testp.f file referred to above:
```
#include <stdio.h>
extern void hello_();
int main(int argc, char **argv) {
  printf("Hello from c.\n");
  hello_();
  return 0;
}
```
and
```
      subroutine hello
      print *,"Hello from f."
      end
```

Hope this helps....dac

**Comment by jaimergp** [comment]
I don't see any obvious errors here. The standalone `gfortran` test compilation works fine, so the variables are being set correctly, I'd say. 

@dacase, could you print the output of `env | sort` for both environments (with conda compilers and with system compilers)? I don't immediate have access to a Mac here, sorry!

**Comment by jchodera** [comment]
Anyone have any additional ideas here? Would be great if we could figure this out!

**Comment by simonbray** [comment]
The problem seems clear; the `rpath` stuff is not getting added to the compiler flags correctly. Unfortunately I don't have enough knowledge about conda builds to find the solution.

@beckermr, would you mind taking another look at this? I tried a few different things out, as you can see from the commit history, but didn't really make any progress.

**Comment by beckermr** [comment]
I cannot see any of the builds on azure. I think they may be too old. Let's bump it again.

@conda-forge-admin, please rerender

**Comment by beckermr** [comment]
@conda-forge-admin, please restart ci

**Comment by beckermr** [comment]
Well @simonbray, the CI isn't even running. I think it is best to start a new PR.

**Comment by beckermr** [comment]
@conda-forge-admin, please restart ci

**Comment by beckermr** [comment]
You might try fixing the merge conflict (which I cannot do). This could be the problem.

**Comment by simonbray** [comment]
Yes, looks like that fixed it

**Comment by beckermr** [comment]
huzzah!

**Comment by beckermr** [comment]
Lots of unrelated errors to linking:

```
/usr/local/miniconda/conda-bld/ambertools_1576678591386/work/conda_build.sh: line 16: ./update_amber: No such file or directory
```

Once these are fixed, ping me again!

**Comment by jchodera** [comment]
@simonbray : Looks like the issue is with the retrieval of the tarball:
```
Downloading source to cache: master_e696ff7b4d.tar.bz2
Downloading https://bitbucket.org/simonbray/ambertools/get/master.tar.bz2
Error: HTTP 000 CONNECTION FAILED for url <https://bitbucket.org/simonbray/ambertools/get/master.tar.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
WARNING:conda_build.source:Error: HTTP 000 CONNECTION FAILED for url <https://bitbucket.org/simonbray/ambertools/get/master.tar.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
WARNING conda_build.source:download_to_cache(84): Error: HTTP 000 CONNECTION FAILED for url <https://bitbucket.org/simonbray/ambertools/get/master.tar.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.
Could not download https://bitbucket.org/simonbray/ambertools/get/master.tar.bz2
```
Why are we grabbing the tarball from `https://bitbucket.org/simonbray/ambertools/get/master.tar.bz2`? Shouldn't we use an official source distribution location? I imagine @dacase could give us a URL or make the official source tarball available somewhere for this purpose.

**Comment by simonbray** [comment]
@jchodera, yes, the problem is with the tarball. I think I fixed it, am just testing locally at the moment.

Yes, it would be better to install from an official link, as you say. Currently I don't think such a link exists.

**Comment by dacase** [comment]
```
Yes, it would be better to install from an official link, as you say. Currently I don't think such a link exists.
```

Look here 
```
https://ambermd.org/downloads/AmberTools19.tar.bz2.cmlqap
```

(It still *might* be better to get a subset of AmberTools (aka ambermini): that would insulate this project from problems with AmberTools that involve parts of the code that you don't care about, and would speed up builds, etc.  But I can see arguments for having just one giant AmberTools package that everyone uses.)

**Comment by beckermr** [comment]
There is a second issue on it not finding a script which I posted above as well.

**Comment by dacase** [comment]
`./update_amber: No such file `

Not sure what directory you are in.  The `update_amber` script is in the top-level directory when you extract files from `AmberTools19.tar.bz2`.

**Comment by hainm** [comment]
> ./update_amber: No such file

Because of the missing tarfile like @jchodera pointed out. 
> Looks like the issue is with the retrieval of the tarball:

**Comment by beckermr** [comment]
@dacase this is a line from the CI scripts, not my machine. Def check there.

**Comment by simonbray** [comment]
@beckermr, hopefully this will fail in a more useful way this time.

As a side note, I updated the tarball url (thanks a lot @dacase for the link) but it seems conda doesn't recognise the `tar.bz2.cmlqap` extension. So the untarring and patching is now done in the `build.sh`, which I guess isn't ideal.

**Comment by jchodera** [comment]
Great! We're back to [the `rpath` issues](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=104739&view=logs&jobId=9c5ef928-2cd6-52e5-dbe6-9d173a7d951b&j=9c5ef928-2cd6-52e5-dbe6-9d173a7d951b&t=113b264d-9551-5065-da10-7eb3bdeaf1bc) with the `osx` build now, which we were originally hoping to get @beckermr's insight on!

**Comment by beckermr** [comment]
OK. So you still don't have the rpaths set here when the code is testing the compilers:

```
x86_64-apple-darwin13.4.0-clang -fPIC -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -o testp testp.c.o testp.f.o -L$BUILD_PREFIX/lib/gcc/x86_64-apple-darwin13.4.0/7.3.0/../../../ -lgfortran -w 
```

This line needs the rpaths. They are in LDFLAGS so somewhere in the configure scripts or w/ for your package you need to inject these into those lines.

**Comment by dacase** [comment]
```
OK. So you still don't have the rpaths set here when the code is testing the compilers:
```

Problem (for me) is knowing what these rpaths should be.  They are never needed for ordinary (user) builds of AmberTools on OSX.  (This includes building conda packages, but using locallly-installed compilers.)  Problem arises when we are forced to use the compilers that conda-forge/conda-build selects for us.  

If someone can figure out what the rpaths are supposed to be, it should be straightforward to add that info to the configure script (via some flag that is only set for conda-forge builds.)  But I think this is beyond my skill set.  (I've never used conda-forge; and earlier attempts to use conda's compilers, rather than my own, have also failed, for me.)

**Comment by beckermr** [comment]
They are in the LDFLAGS that conda injects into the build environment. So you simply need the ambertoosl build system to respect those flags.

**Comment by beckermr** [comment]
The actual flag values change depending on the invocation of conda build, so it is best to simply use them as is.

**Comment by jaimergp** [comment]
> As a side note, I updated the tarball url (thanks a lot @dacase for the link) but it seems conda doesn't recognise the tar.bz2.cmlqap extension. So the untarring and patching is now done in the build.sh, which I guess isn't ideal.

You can use [`fn`](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#filename) to rename the download file before extraction, so maybe that's one way to avoid doing it in the `build.sh` script.

**Comment by beckermr** [comment]
@dacase See this line in the CI logs: https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=104739&view=logs&j=4b3757f9-99c5-5891-6c0c-93d7030cdf7d&t=0a2070c1-8027-59fc-ddea-6aec050600c1&l=149

These flags need to be used by all linking invocations done by the compiler. Do not copy them as they appear because conda build is rewriting the PATH for clarity. Instead have the build scripts reference the whole variable `$LDFLAGS` when it is linking.

**Comment by dacase** [comment]
```
have the build scripts reference the whole variable $LDFLAGS when it is linking.
```

OK: I play with this a bit.  It's certainly easy to just add LDFLAGS to our build commands -- we essentially build our own command lines now, precisely to avoid have a dependency on things in the user's environment; but that sounds like a bad thing to do for a conda build.

That said, if someone else has time to try this out, have at it.  I'm extraordinarily busy this week, so may not be able to do much.  Plus, it would take me some time to figure out exactly which configure scripts are being used here.

**Comment by dacase** [comment]
```
conda doesn't recognise the tar.bz2.cmlqap extension.
```
OK: i've set things up so you can remove the `cmlqap` extension.  If conda knows what to do with `tar.bz2`, that should help.

**Comment by jchodera** [comment]
> OK: i've set things up so you can remove the cmlqap extension. If conda knows what to do with tar.bz2, that should help.

Thanks so much, @dacase!

**Comment by dacase** [comment]
Happy New Year everyone.  I've been trying hard to use the anaconda-supplied compilers on OSX. The following web page seems relevant (but maybe already known to everyone here?)
```
https://docs.conda.io/projects/conda-build/en/latest/resources/compiler-tools.html
```

As I read this (and read the error logs from my attempts), conda builds require the Xcode 10.9 SDK to be present on the build machine.  (Not sure if/how this changes for conda-forge).

Anyway, here's how things stand with my tests:

* The tests of the C and Fortran compilers at the beginning of the configure process are now fine. (I'm using `$LDFLAGS` from conda now: the stock configure refines LDFLAGS.)

* Unfortunately, the build fails at the first attempt to build an executable file (in antechamber, am1bcc).  The compiler invocation looks very close to the one used in the tests at the beginning, but now I get this error:
```
ld: warning: ignoring file /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/libSystem.tbd, file was built for unsupported file format ( 0x2D 0x2D 0x2D 0x20 0x21 0x74 0x61 0x70 0x69 0x2D 0x74 0x62 0x64 0x2D 0x76 0x33 ) which is not the architecture being linked (x86_64): /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib/libSystem.tbd
Undefined symbols for architecture x86_64:
  "___error", referenced from:
      _eprintf in eprintf.o
      _esystem in eprintf.o
  "___memcpy_chk", referenced from:
      _trimwhitespace in am1bcc.o

....etc.....
```

Note that the `libSystem.tbd` referenced above starts like this:
```
--- !tapi-tbd-v3
archs:           [ x86_64 ]
```

I apologize if I am just adding noise, and no solutions.  It seems like we are close, but the insistence on using compilers provided by anaconda, rather than the ones that are already present on the build platform being used, seems to present tough problems.

I'll sign off here: I simply can't afford to spend more time on this, and I probably don't have the right skill set to solve it anyway.

**Comment by beckermr** [comment]
We have been looking at a linking error for gfortran here: https://github.com/conda-forge/gfortran_osx-64-feedstock/pull/10

I wonder if this is related.

**Comment by dacase** [comment]
The error I am seeing is with pure C code, no gfortran connection.

**Comment by jchodera** [comment]
@dacase: Happy New Year, and HUGE thanks for pushing this so far forward!

@jaimergp and @lnaden: Any ideas here? You folks have much more experience with the anaconda compiler suite.

**Comment by jaimergp** [comment]
I'd be happy to help here! I have been trying to build the `ppc64le` version too in this other PR (#16), so I am a bit more familiar with the compilation process now. Unfortunately, I don't have any MacOS machine handy. Does anybody have access to a headless instance I can log in and debug this?

**Comment by jaimergp** [comment]
The error we are seeing right now (line 6944) is a bit weird. My hunch is that due to MacOS case insensitivity, some file is importing `xdrfile/VERSION` as a source code file (and its contents are simply a disclaimer  `Code is from MDTRAJ (https://github.com/mdtraj/mdtraj), commit aa1c91f3ab6b0f9e9f1d0c790d2b5bff7c83ece4`), and that's why it fails. Notice how the error says `xdrfile/version:1:1: error: unknown type name 'Code'`, but the actual file is `xdrfile/VERSION`.

Does that make any sense? Is there any part of the code that tries to call `xdrfile/version`?

**Comment by jaimergp** [comment]
Maybe [these flags](https://stackoverflow.com/questions/26182372/configure-osx-clang-to-be-case-sensitive-to-include-statements) are useful?

**Comment by jaimergp** [comment]
Oops, my messages were about the error we are seeing in Azure for OS X. The Linux builds are failing because `zlib` is not being found.

With respect to the errors @dacase is seeing, it looks like a mismatch between the SDK the Anaconda compilers are expecting and the one present in your system. [Check this SO answer](https://stackoverflow.com/a/55798942).

**Comment by jaimergp** [comment]
Superseded by #18

**Pull request closed without merging**
