### PR TITLE
Add python

### PR DESCRIPTION
**Pull request by simonbray**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by simonbray** [comment]
@bgruening @hainm any comments?

**Comment by bgruening** [comment]
@conda-forge-admin, please re-render

**Comment by bgruening** [comment]
@conda-forge-admin, please re-render

**Comment by bgruening** [comment]
@conda-forge-admin, please re-render

**Comment by simonbray** [comment]
Re-opened here: https://github.com/conda-forge/ambertools-feedstock/pull/3

**Pull request closed without merging**
